# Generated by Django 2.2.6 on 2019-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=models.CharField(max_length=200, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Servico'),
        ),
    ]
