# Generated by Django 2.2.6 on 2019-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0002_auto_20191006_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='nomePrincipal',
            field=models.CharField(db_index=True, default='default', max_length=200, unique=True, verbose_name='Nome Principal'),
            preserve_default=False,
        ),
    ]
