# Generated by Django 2.2.6 on 2019-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0003_tiposervico_nomeprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='fraseDestaque',
            field=models.CharField(default='default', max_length=200, verbose_name='Frase'),
            preserve_default=False,
        ),
    ]
