# Generated by Django 2.2.6 on 2019-10-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0006_auto_20191006_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DestaqueServicos',
            new_name='DestaqueServico',
        ),
    ]
