# Generated by Django 2.2.6 on 2019-10-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0007_auto_20191006_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaqueservico',
            name='dislikes',
            field=models.IntegerField(default=0, max_length=10000, verbose_name='dislikes'),
        ),
        migrations.AddField(
            model_name='destaqueservico',
            name='likes',
            field=models.IntegerField(default=0, max_length=10000, verbose_name='likes'),
        ),
    ]
