# Generated by Django 2.2.6 on 2019-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0008_auto_20191006_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='nome')),
                ('endereco', models.CharField(max_length=200, verbose_name='Imagem')),
            ],
            options={
                'db_table': 'fotoCarousel',
            },
        ),
    ]
