# Generated by Django 2.2.6 on 2019-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0009_fotocarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaqueservico',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislikes'),
        ),
        migrations.AlterField(
            model_name='destaqueservico',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
    ]
