# Generated by Django 2.2.6 on 2019-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0010_auto_20191006_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaqueservico',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='ordem'),
        ),
    ]
