# Generated by Django 2.2.6 on 2019-10-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0011_destaqueservico_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tag',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='destaqueservico',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meuSite.Servico'),
        ),
    ]
