# Generated by Django 2.2.6 on 2019-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0012_auto_20191007_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tag',
            field=models.CharField(default=' ', max_length=100, verbose_name='Tag'),
        ),
    ]
