# Generated by Django 2.2.6 on 2019-12-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuSite', '0015_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tag',
            field=models.SlugField(default=' ', max_length=100, verbose_name='Tag'),
        ),
    ]
